### ISSUE TITLE
Question from user on what went wrong with his upgrade.

### ISSUE THREAD

**Issue by ktsakalozos** [canonical-web-and-design/microk8s.io#115]
@evilnick, a user asked on #microk8s, how/why an upgrade broke his deployment:

Here are some good practices you should consider in order to have a more stable
setup.
- Do not follow the latest channel. The latest channel will get major upgrades when upstream Kubernetes releases.
For example the 1.16 release (next week) will transition all MicroK8s instances to the flannel cni and introduce clustering.
When stability is important you should follow a specific channel with for example sudo snap install microk8s --classic --channel=1.15/stable.
Please have a look at the release scheme we follow at https://microk8s.io/docs/release-channels.
- Snap upgrades happen transparently in the background but you can schedule them in a convenient to you time.
You can do that with snap set system refresh.timer as shown in https://snapcraft.io/docs/keeping-snaps-up-to-date
You can introduce a delay to upgrades of critical sections of your infrastructure so as to first test the upgrade process in a non critical sections.
- To have full control on what revisions land and when you could consider setting up a proxy https://docs.ubuntu.com/snap-store-proxy/en/
- Please subscribe to the microk8s tag at https://discuss.kubernetes.io/tags/microk8s so you get announcements.
- We obviously do not want to break people during upgrades. So we run upgrade tests before every release.
If you are interested I could show you how the upgrade is tested. Should we find that we have gaps
important to you, we have to close them so we do not break you in the future.
Here is the upgrade test we have https://github.com/ubuntu/microk8s/blob/master/tests/test-upgrade.py
- In the future, if you see some unexpected behavior please run a microk8s.inspect and attach the produced tarball on an issue at
https://github.com/ubuntu/microk8s/issues .

**Comment by evilnick** [comment]
@ktsakalozos can you let me know which of these you still feel needs to be addressed

**Comment by pmahnke** [comment]
Discussed with @evilnick, closing.
