### ISSUE TITLE
LXD/LXC instructions to add

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/microk8s.io#146]
We should add the following to docs when there is a standard profile:

---
## LXD/LXC

MicroK8s can be run inside an LXC container. The only caveat here is that the
container requires certain settings which are not part of the default LXD
profile.

Two profiles are available in the [MicroK8s repository][profile] - one for
LXD using ZFS storage, and one for the default storage. Use one of
these files to create a new profile:

```bash
lxc profile create mk8s
lxc profile edit mk8s < microk8s.profile
```
... and then run a container with:

```bash
lxc launch -p default -p mk8s ubuntu:18.04 microk8s-container
```

You can then launch a shell in the container and perform commands as
usual:

```bash
lxc exec microk8s-container shell
```

You can also obtain the IP address of the container by running:

```bash
lxc list
```

this can be used to access the API.

**Comment by SirSamTumless** [comment]
@evilnick Who needs to review this?

**Comment by evilnick** [comment]
fixed in discourse
