### ISSUE TITLE
no dashboard access via the instructions

### ISSUE THREAD

**Issue by kronik22** [canonical-web-and-design/microk8s.io#159]
I have followed the instructions for using the dashboard add-on; however, i am not able to access the dashboard following the instructions provided. i have selected the non-rbac option, copied my token, enabled the proxy via an ssh terminal and copied the dashboard url into a browser. With the loopback address 127.0.0.1 i do not connect to the dashboard. If i change the loopback IP address to the host IP address, i get the dashboard authentication process. I paste the token into the web field, select the signin button, but nothing happens. The dashboard remains in the authentication webpage.

https://microk8s.io/docs/addon-dashboard

**Comment by evilnick** [comment]
Hi, I have confirmed on both 18.04 and 19.10 that the dashboard add-on works as per the published instructions, so something else is going on here. It would be useful if you could provide the output from microk8s.inspect
