### ISSUE TITLE
New docs: alias section removed

### ISSUE THREAD

**Issue by yosheeck** [canonical-web-and-design/microk8s.io#172]
**What's the issue:**
In recent version of the docs the whole section about adding alias has been removed.

**Expected:**
In documentation for our project https://mojaloop.io/documentation/deployment-guide/ we rely on a fact that section about aliast is there.

**Proposed fix:**
Add back the missing section.
Or reject that ticket, which means we need to adjust documentation in our project (and probably some other dependent project will need that too).

**Details:**
Link to old version: https://github.com/canonical-web-and-design/microk8s.io/blame/7aeaad66ecd8d961f9527b7328cfae22398ccbdf/docs/index.md
Link to new version: https://github.com/canonical-web-and-design/microk8s.io/blame/master/docs/index.md

**Comment by pmahnke** [comment]
@yosheeck thanks for filing this.  I am adding the head docs person to this to review.

**Comment by evilnick** [comment]
Apologies for breaking your docs. As you can probably tell, the entire site was rewritten recently and I hope that you will find that it is much improved in terms of content. Inevitably this has resulted in some changes in content and where in the docs that content is located. I will add back in a note about aliases and update this issue

**Comment by davix** [comment]
There is a typo in the doc:
```
alias kubectl='microk8s.kubetcl'
```
The last three letters should be `ctl`.
