### ISSUE TITLE
Dashboard documentation does not work

### ISSUE THREAD

**Issue by supersexy** [canonical-web-and-design/microk8s.io#181]
The [docs](https://microk8s.io/docs/addon-dashboard) for dashboard addon do not work. 
I get to the login screen, select the "Token" option to login and paste the long token string that was generated by the commands described in that guide. I click the signin button and nothing happens.

I now stop evaluating microk8s - this seems to be in a very early stage. I really do not understand why you are advertising this at the login screens of server installations - it gives a very bad impression. I would not write that if it was not Ubuntu. My god, what a bad experience, I can not believe it, this is _Ubuntu!!!_ - you can not do that, it is awful, it will destroy everything. Stop it!

**Comment by evilnick** [comment]
I'm really sorry you have had difficulty with the dashboard - a few other people have reported problems, but we can't replicate them here. I have run through the instructions on a clean install in 18.04 and 19.10 and they work as described. We are really keen to make sure that everyone can use this feature easily though. It would help a great deal if we could work out why it isn't working for you - is it possible you could run microk8s.inspect and send me the report file it produces?

**Comment by ktsakalozos** [comment]
@supersexy would you be willing to have a quick call to show us what and how this is failing? It might be something @evilnick and me take for granted and we skip in our docs.

**Comment by AdeAttwood** [comment]
HI @evilnick @ktsakalozos I have just started playing around with this. I have had this issue twice now on do droplets. Run through the first time, then kill the droplet and started again running into the same issue. I have run `microk8s.inspect` and have the `tar.gz` file ready to go. I will keep the droplet for a bit for anything else.

**Comment by ktsakalozos** [comment]
@AdeAttwood running MicroK8s in a VM is a very important information I was missing. As you can read in the upstream docs [1], the behavior you report is expected since the dashboard should not be exposed to remote users.

In the PR above we have revised the docs page to use an alternative approach that can work around the dashboard exposing limitations.

Thank you for your feedback.

[1] https://github.com/kubernetes/dashboard/blob/master/docs/user/accessing-dashboard/1.7.x-and-above.md

**Comment by AdeAttwood** [comment]
Hi again all, I have been playing around with this and its all working nicely. One thing I did find helpful that wasn't in the docs is the `microk8s.config` command, this was helpful with configuring the local `kubectl`command for running `kubectl proxy` locally to access the dashboard.

Thanks for the replies.

**Comment by evilnick** [comment]
Thanks for the update. I think we are going to need to add a section on networking and proxies. Particularly when dealing with mk8s in a container/vm
