### ISSUE TITLE
Raspberry PI instructions need updating

### ISSUE THREAD

**Issue by jfmatth** [canonical-web-and-design/microk8s.io#196]
There are a few of us having issues getting MicroK8s to run on a Pi.

The instructions say to modify /boot/firmware/cmdline.txt when in fact, for myself and others, modifying /boot/firmware/nobtcmd.txt instead.  Per https://github.com/ubuntu/microk8s/issues/778

Hope this helps.

**Comment by evilnick** [comment]
Fixed in #198
