### ISSUE TITLE
Failed to enable kubeflow

### ISSUE THREAD

**Issue by DFranc-D** [canonical-web-and-design/microk8s.io#207]
Tried the new release microk8s 1.17 to test kubeflow but at the end it failed.
Ran inspect, restarted microk8s, reset microk8s cluster, and even rebooted my VM  Ubuntu 18.04 running inside VMware Playstation with a Kali Linux host on an HP ProBook. 
I even ran snap remove microk8s 1.17 and ran "snap install microk8s --classic --channel=1.17/stable" ... but to no avail.
One thing I did notice while the hangs occurred was that the VM threw low disk space while the GUI was opened. I did ran apt-clean and will add more space to my / root to see if that makes a difference...
franc@master-node-ub1804:~$ microk8s.enable kubeflow
Enabling dns...
Enabling storage...
Enabling dashboard...
Enabling ingress...
Enabling rbac...
Enabling juju...
Deploying Kubeflow...
ERROR controller "uk8s" already exists

Command '('microk8s-juju.wrapper', 'bootstrap', 'microk8s', 'uk8s')' returned non-zero exit status 1
Failed to enable kubeflow

**Comment by DFranc-D** [comment]
Here is another intersting find... this time I switched hosts (RHEL 7.7) and hypervisor (KVM/QEMU)...  and here is what I get when simply trying to just "microk8s.enable kubeflow"

[franc@master ~]$ microk8s.enable kubeflow
Enabling dns...
Enabling storage...
Enabling dashboard...
Enabling ingress...
Enabling rbac...
Enabling juju...

Write on output file failed because No space left on device

writer: failed to write data block 1023

Failed to write /var/snap/microk8s/1107/tmp/juju/bin/juju, skipping
cp: cannot stat ‘/var/snap/microk8s/1107/tmp/juju/bin/juju’: No such file or directory

Command '('microk8s-enable.wrapper', 'juju')' returned non-zero exit status 1
Failed to enable kubeflow

**Comment by kwmonroe** [comment]
@DFranc-D I ran into something similar in 1.18.  For me, the default constraints were too low.  I needed at least 12G ram and 50g disk to get `microk8s.enable kubeflow` to work (#256).

Can you confirm how much free disk space you had on your VMs?

**Comment by evilnick** [comment]
Fixed in discourse
