### ISSUE TITLE
Missing namespace in 'Using images' docs page

### ISSUE THREAD

**Issue by florian-koenig** [canonical-web-and-design/microk8s.io#210]
The page https://microk8s.io/docs/registry-images says:

> Note that when we import the image to MicroK8s we do so under the k8s.io namespace.

However, the following call in the description is missing the namespace, which prevents then example from working:

> microk8s.ctr image import myimage.tar

It should be

> microk8s.ctr -n k8s.io image import myimage.tar

and further down

> microk8s.ctr -n k8s.io images ls

Without the '-n k8s.io', Kubernetes is unable to find the cached image and fails when starting the deployment.

**Comment by florian-koenig** [comment]
I found out what must have caused the seemingly incorrect call in the docs: From microk8s 1.17 onwards, the k8s.io namespace is set as default (see https://microk8s.io/docs/release-notes). I was using 1.15. Would be helpful, nonetheless, to add this hint to the docs. Thanks

**Comment by evilnick** [comment]
thanks @florian-koenig
