### ISSUE TITLE
Add zfs and offline install in the menu

### ISSUE THREAD

**Issue by balchua** [canonical-web-and-design/microk8s.io#211]
Currently under the 'Alternate install method' only the following items are shown.
- Windows 10
- MacOS
- Raspberry PI /ARM

Requesting to add:
- ZFS
- Offline Deployment

It is not easy to find these information from its home page, unless you go to the " Alternate install method"

**Comment by ktsakalozos** [comment]
@balchua good point. Yes offline deployment should be mentioned in the docs. I am not sure about the ZFS setup. I feel we should work on MicroK8s to have it work out of the box with ZFS. This is kind of urgent since the the upcoming will be on zfs by default.

**Comment by balchua** [comment]
Can we instead, for the meantime add zfs in the trouble shooting guide?  Maybe some users will not be able to migrate to the latest for sometime?

**Comment by evilnick** [comment]
offline is in the nav. thanks @balchua
