### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by jordiblasco** [canonical-web-and-design/microk8s.io#219]
## Summary

The current [addon-dashboard documentation](https://github.com/canonical-web-and-design/microk8s.io/blob/master/docs/addon-dashboard.md) doesn't describe the process of setting up the dashboard.

[Please describe the issue.]
The port-forward leads to certificate issues. 
As explained in the [Accessing Dashboard 1.7.x and above] (https://github.com/kubernetes/dashboard/blob/master/docs/user/accessing-dashboard/1.7.x-and-above.md) the process is not that simple anymore.

_IMPORTANT: HTTPS endpoints are only available if you used Recommended Setup, followed Getting Started guide to deploy Dashboard or manually provided --tls-key-file and --tls-cert-file flags. In case you did not and you access Dashboard over HTTP, then Dashboard can be accessed the same way as older versions._

Unfortunately, the process described in the older versions is also not accurate:
https://github.com/kubernetes/dashboard/blob/master/docs/user/accessing-dashboard/1.6.x-and-below.md

## Process

```
microk8s.enable dashboard
token=$(microk8s.kubectl -n kube-system get secret | grep default-token | cut -d " " -f1)
microk8s.kubectl -n kube-system describe secret $token
microk8s.kubectl port-forward -n kube-system service/kubernetes-dashboard 10443:443 --address 0.0.0.0
```

## Current and expected result
Following the current instructions defined in this document, it leads to a web browser error "Your connection is not private".

**Comment by evilnick** [comment]
Changes to the port-forwarding and use of dashboard are now online at https://microk8s.io/docs/addon-dashboard
If you are still having an issue, please follow the 'Help improve this document in the forum' link at the bottom of that page
