### ISSUE TITLE
The instructions to access the dashboard via a browser are incomplete.

### ISSUE THREAD

**Issue by geosp** [canonical-web-and-design/microk8s.io#221]
## Summary

The instructions to access the dashboard via a browser are incomplete and result in errors during execution. Please correct the documentation so it reflects the correct steps to access the dashboard.

## Process

Execute the following commands:

1. `sudo microk8s.enable dashboard`
2. `token=$(microk8s.kubectl -n kube-system get secret | grep default-token | cut -d " " -f1)
microk8s.kubectl -n kube-system describe secret $token` 
3. `microk8s.kubectl port-forward -n kube-system service/kubernetes-dashboard 10443:443`
4. Navigarte to https://127.0.0.1:8001

## Current Steps

- Step number 3 produces an error.
- The URL  https://127.0.0.1:8001 is wrong it should be https://127.0.0.1:10443
- When opening URL https://127.0.0.1:10443 using Chrome you are not able to access the dashboard because the certificate is invalid. 
- When opening using Firefox you can access the login screen after accepting the risk.
- The screen asks for a token.

## Expected Results with Corrected Steps

* I expected for the scree to display the dashboard without issues at https://127.0.0.1:8001.

Instead I had to execute these commands:

1. `sudo microk8s.enable dashboard`
2. `microk8s.kubectl port-forward -n kube-system service/kubernetes-dashboard 10443:443`
3. `token=$(sudo microk8s.kubectl -n kube-system get secret | grep default-token | cut -d " " -f1) | sudo microk8s.kubectl -n kube-system describe secret $token`. Example output:
```
Name:         default-token-xcsnj
Namespace:    kube-system
Labels:       <none>
Annotations:  kubernetes.io/service-account.name: default
              kubernetes.io/service-account.uid: d1c5bfb3-b242-43d6-a9d7-afec8ab29b63

Type:  kubernetes.io/service-account-token

Data
====
ca.crt:     1103 bytes
namespace:  11 bytes
token: eyJhbGciOiJSUzI1NiIsImtpZCI6InZ2TVl5aTZ0WGVJTnhKMkFaYkJnZmVpRS1ZeHZ3dk54WXJFQWQ3cXBzTkEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLXhjc25qIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJkMWM1YmZiMy1iMjQyLTQzZDYtYTlkNy1hZmVjOGFiMjliNjMiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.RX6Y_92-SmCf_LptFstdrUG4oUfrwKlf8rTl8r3ixOUDCMgJ0j236KQRCyFcJVcAmzliTTVr3OcSlXf6INbPMm1hHVNg-e-RrOwxb_sQg78WKT-sfjlP8bKdUa8tge6SHPA2f_qx-KvkvT4yL6_FWP0pMX4sd_6xewwF8UIojgSiXqXIfeGC63I7ainN7nF0veh-EiYR_xwygS9RTvmgIYgfdYUNuoexyB_iHv31ZUgDdxBEywefE4_ui_yI1W2TX6bKwPbXMDhFOfv-BLWKB5B3oax7JCxik8s4RQA1tpSIhfYYYl4drc423D1t8ECG-6P8J9yIujQg_2bYVTPZeQ
```
4. Use Firefox to open the URL https://127.0.0.1:10443
5. In the login screen select token authentication and used the token form step 3.

## Screenshot

![Screenshot from 2020-02-11 10-22-08](https://user-images.githubusercontent.com/20133884/74250384-83f84200-4cb8-11ea-9113-a74f8c7e128c.png)

## Browser details

Use Firefox since it allows you to bypass certificate errors.

**Comment by evilnick** [comment]
The recommended way to access the dashboard has changed and the docs updated. See <https://microk8s.io/docs/addon-dashboard>
