### ISSUE TITLE
Enable dashboard in in an RBAC enabled setup

### ISSUE THREAD

**Issue by sromano1992** [canonical-web-and-design/microk8s.io#236]
## Summary

I was trying to use the guide at [this](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/README.md#admin-privileges) link to enable access the Kubernetes dashboard in a RBAC enabled setup but each of the following steps failed:

1. Create Service Account
2. Create ClusterRoleBinding
3. Bearer Token
## Process

1. Install multipass and the microk8s using [this](https://ubuntu.com/tutorials/install-microk8s-on-windows#2-spinning-up-a-vm-with-microk8s) guide
2. enable Kubernetes dashboard: `microk8s.enable dashboard`
3. try to create an use using the [create a user with restricted permissions](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/README.md#admin-privileges)

Here you will have the error I described in the _Summary_ section.

## Current and expected result
The issue was the following: 

```
ubuntu@kubeflow:~/kube$ microk8s.kubectl apply -f createuser.yaml
Error from server (NotFound): error when creating "createuser.yaml": namespaces "kubernetes-dashboard" not found
```

The expected result was to have the token to access the Kubernetes dashboard.

## Browser details
**I was able to resolve** replacing, in each of the following steps, the word "kubernetes-dashboard" with "kube-system":

1. Create Service Account
2. Create ClusterRoleBinding
3. Bearer Token

**Comment by evilnick** [comment]
@sromano1992 I believe this issue is solved in the current docs. Please see <https://microk8s.io/docs/addon-dashboard>
You can comment by following the 'Help improve this documentation...' link at the bottom of the page
