### ISSUE TITLE
kubeflow

### ISSUE THREAD

**Issue by zshenkle** [canonical-web-and-design/microk8s.io#240]
## Summary

[Please describe the issue.]

## Process

[List the steps to replicate the issue.]

## Current and expected result

[Describe what happened and what you expected.

## Screenshot

[If relevant, include a screenshot.]

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by anthonydillon** [comment]
Can you please provide more information and reopen please.
