### ISSUE TITLE
Wrong link in "Download MicroK8s for Windows" button

### ISSUE THREAD

**Issue by ktsakalozos** [canonical-web-and-design/microk8s.io#241]
## Summary

On the landing page, microk8s.io the file you download from the "Download MicroK8s for Windows" button is the multipass installer. It should be the MicroK8s installer (https://github.com/ubuntu/microk8s/releases/download/installer-v1.0.0/microk8s-installer.exe)

## Process

Go to https://microk8s.io/
Under "Get started with MicroK8s" click on Windows
Click the "Download MicroK8s for Windows" button

## Current and expected result

Currently you get the multipass installer.

You should get the MicroK8s installer.

Note that the button code on github (https://github.com/canonical-web-and-design/microk8s.io/blob/master/index.html#L261) correctly points to the MicroK8s installer.

**Comment by evilnick** [comment]
This seems to be caused by 'installversion.js' rewriting the download url. 

I have removed the classes that trigger the rewrite in #242. If anyone wants to fix up the underlying code, go ahead
