### ISSUE TITLE
document larger constraints for kubeflow

### ISSUE THREAD

**Issue by kwmonroe** [canonical-web-and-design/microk8s.io#256]
## Summary

`microk8s.enable kubeflow` doesn't work with the documented multipass VM constraints

## Process

I followed the [docs](https://github.com/canonical-web-and-design/microk8s.io/blob/master/docs/install-alternatives.md#multipass) for setting up a multipass VM for microk8s:

```bash
multipass launch --name microk8s-vm --mem 4G --disk 40G
```

I then installed the microk8s 1.18/stable snap and ran `microk8s.enable kubeflow` from within the VM.  I did this on `macOS 10.14.6` with `multipass 1.1.0`, though I expect any platform would behave similarly. 

## Current and expected result

The 4G VM OOM'd pretty quickly and the microk8s process was killed.  I tried again with `--mem 8G` and while it did eventually work, kubeflow took ~3 hours to deploy and settle down.  I tried again with `--mem 12G` and this went much better, settling after less than an hour.

During each attempt, i noticed the kubeflow deployment was using somewhere between 30 and 35G of disk space.  This is dangerously close to the `--disk 40G` default constraint, and I think we'll run out of disk as soon as people try to actually use kubeflow.

I think we should add a callout next to the [kubeflow addon](https://github.com/canonical-web-and-design/microk8s.io/blob/master/docs/addons.md#L74) that warns users about minimum constraints for a usable microk8s/kubeflow environment.  For me, that was 12G of memory and 50G of disk.

**Comment by evilnick** [comment]
Fixed in discourse
https://discuss.kubernetes.io/t/alternative-installs-macos-windows-10-multipass/11257
