### ISSUE TITLE
Proxy windows download binary to github

### ISSUE THREAD

**Issue by pmahnke** [canonical-web-and-design/microk8s.io#280]
link in redirects.yaml that points /download/install.txt to e.g. /download/microk8s-202004-install.exe, then we have nginx proxy that second URL to the appropriate github release

**Comment by nottrobin** [comment]
@pmahnke is this on hold?

**Comment by pmahnke** [comment]
No. We need to push is to do it.

**Comment by nottrobin** [comment]
I don't suppose something like https://github.com/canonical-web-and-design/multipass.run/pull/103 would be sufficient here would it?
