### ISSUE TITLE
URL with www does not redirect to microk8s.io

### ISSUE THREAD

**Issue by barrymcgee** [canonical-web-and-design/microk8s.io#304]
Problem:

<img width="1035" alt="Screenshot 2020-08-06 at 20 03 55" src="https://user-images.githubusercontent.com/505570/89571670-fbe69580-d81f-11ea-9962-5efa5f4989fc.png">

Expected:

https://microk8s.io should redirect to https://microk8s.io

**Comment by carkod** [comment]
Should we open an RT for this?

**Comment by jlosito** [comment]
@carkod @barrymcgee you should be all set now.

```
$ curl -s -o /dev/null -w "%{http_code}" http://www.microk8s.io
301
```

**Comment by nottrobin** [comment]
Thanks @jlosito, yep seems to work.
