### ISSUE TITLE
Add note in docs about allow-privileged and PodSecurityPolicy

### ISSUE THREAD

**Issue by davecore82** [canonical-web-and-design/microk8s.io#305]
## Summary

There is no clear documented way to allow privileged containers in microk8s. 

From what I understand, to allow privileged containers you need to add the following line to /var/snap/microk8s/current/args/kube-apiserver:

`--allow-privileged`

And then restart the microk8s api server daemon:

`sudo systemctl restart snap.microk8s.daemon-apiserver`

But then it's also possible to use PodSecurityPolicy in combination with --allow-privileged if you want to allow privileged containers and restrict who is allowed to create them.

To do that, you add a PodSecurityPolicy to /var/snap/microk8s/current/args/kube-apiserver:

`--enable-admission-plugins="PodSecurityPolicy"`

And restart the service:

`sudo systemctl restart snap.microk8s.daemon-apiserver`

Extra documentation on how to use these pod security policies would be useful too.

**Comment by evilnick** [comment]
Just to follow up on this - I am working through a list of extra stuff to add to the MicroK8s docs, so I should get to this shortly. Thanks for the suggestion.

**Comment by evilnick** [comment]
This has been added to the config pages
