### ISSUE TITLE
HA docs spelling issues

### ISSUE THREAD

**Issue by alxchalkias** [canonical-web-and-design/microk8s.io#314]
## Summary
Go to https://microk8s.io/docs/high-availability

Fixes needed:
- The control plane must be running on more than one node, so that [...] - **remove comma**

- This documentation describe the steps needed - **describes**

- As before, install an 1.19+ version of MicroK8s on at least two additional - **a 1.19+**

- On the inital node, run: - **initial**

- To complete the removal of the departing , issue the following - **remove space before comma**

**Comment by evilnick** [comment]
Thanks, I took a look through the latest version and fixed a few more issues as well :)
