### ISSUE TITLE
Incorrect Formatting in Step 1 in Getting Started Documentation Page

### ISSUE THREAD

**Issue by mbachari** [canonical-web-and-design/microk8s.io#332]
## Summary
Markdown formatting missing for command 'sudo snap install microk8s --classic --channel=1.19'
## Process
Visiting this page https://microk8s.io/docs 
## Current and expected result
The first step of installation under "1. Install Microk8s", the command section is formatted as normal text
\`sudo snap install microk8s --classic --channel=1.19
Where I believe it should be formatted as code snippet, as follows:
`sudo snap install microk8s --classic --channel=1.19` 
## Screenshot
![Screen Shot 2020-10-04 at 9 25 23 PM](https://user-images.githubusercontent.com/16261145/95032355-2fab3380-0688-11eb-90b2-ae7c7bcce463.png)
## Browser details
https://mybrowser.fyi/report/5f7a74f0fc0a7b00158d2730

**Comment by anthonydillon** [comment]
Thanks you for reporting this issue @mbachari.

@evilnick would you mind updating the code snippet on the k8s discourse please. I don't have access.

**Comment by evilnick** [comment]
done
