### ISSUE TITLE
Link to k8s community points to non-existent tag

### ISSUE THREAD

**Issue by wgx** [canonical-web-and-design/microk8s.io#341]
## Summary

The link under Mac, on the homepage

> Connect with our community and see what others are doing with MicroK8s ›

Points to

> https://discuss.kubernetes.io/tags/microk8s

Which shows:

> Oops! That page doesn’t exist or is private.

**Comment by evilnick** [comment]
The microk8s category was moved when we moved the docs there , it should point to
<https://discuss.kubernetes.io/c/general-discussions/microk8s/26>

**Comment by wgx** [comment]
@evilnick thanks Nick - looks like it was done for Windows but not on the MacOS & Linux partials, fixed now.
