### ISSUE TITLE
keda link broken

### ISSUE THREAD

**Issue by marcinkubica** [canonical-web-and-design/microk8s.io#361]
## Summary

keda link broken from https://microk8s.io/docs/addons#heading--list

## Process

click on https://microk8s.io/docs/addons#heading--list
scroll to the bottom, click `keda` keda: (latest and 1.20 tracks)
## Current and expected result
links to https://microk8s.io/t/addon-keda/14011

404 page not found

## Screenshot

[If relevant, include a screenshot.]

## Browser details

linux, chrome

**Comment by anthonydillon** [comment]
@marcinkubica thank you for taking the time to report this issue. The link has been fixed.

**Comment by marcinkubica** [comment]
@anthonydillon no worries ;)
