### ISSUE TITLE
microk8s ctr image import doesn't work

### ISSUE THREAD

**Issue by rahamohebbi** [canonical-web-and-design/microk8s.io#363]
## Summary

When I run this command to import an exported image, I get the following error message:
microk8s ctr image import myimage.tar

error message:
ctr: open myimage.tar: no such file or directory
An error occurred when trying to execute 'sudo microk8s.ctr image import myimage.tar' with 'multipass': returned exit code 1.

I am using Windows Pro 10

**Comment by rahamohebbi** [comment]
Someone else also reported it here:
https://stackoverflow.com/questions/63624401/microk8s-ctr-image-import-error-import-image

**Comment by SirSamTumless** [comment]
Hi, this is a problem with Microk8s itself, not the webpage, which is here. Please could you refile your issue here; https://github.com/ubuntu/microk8s
