### ISSUE TITLE
Nav link for reporting a bug does not go to the correct <h2>

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-web-and-design/microk8s.io#381]
## Summary

When clicking the link to "Reporting a bug", you are directed to the top of the troubleshooting page. It would appear as though the <h2> for this section is missing its `id`.

**Comment by pmahnke** [comment]
@cjohnston1158 hi!  The reporting a bug links to github, **or** I can't figure out where you mean.  Can you give more details of the page you are on and where the link is?

**Comment by anthonydillon** [comment]
It looks like the "Reporting a bug" navigation items [in the docs](https://microk8s.io/docs/) which should link to the bottom of [the troubleshooting page](https://microk8s.io/docs/troubleshooting) but the id on the heading is missing in the content.

**Comment by anthonydillon** [comment]
@evilnick can you add an id to the title in the troubleshooting content in [the discourse post](https://discuss.kubernetes.io/t/troubleshooting/11267).

**Comment by pmahnke** [comment]
@anthonydillon can you even add an id in markdown?

**Comment by anthonydillon** [comment]
@pmahnke believe so as the "Using the built-in inspection tool" heading has an id

**Comment by pmahnke** [comment]
@evilnick how is this going?

**Comment by evilnick** [comment]
Notwithstanding the handling of headers being generally terrible, the 'reporting a bug' link does have a header which works from the navigation.

**Comment by evilnick** [comment]
see also https://github.com/canonical-web-and-design/canonicalwebteam.discourse/issues/101
