### ISSUE TITLE
Documentation: Missing statement on prerequisite "synchronized time" for adding a node to the cluster

### ISSUE THREAD

**Issue by t-hofmann** [canonical-web-and-design/microk8s.io#385]
To add a node to the cluster the time between node and master needs to be synchronized, in order to do that installing "ntp" on every node of the anticipated cluster before actually adding nodes is often sufficient (e. g. $> sudo apt install ntp). Please add a section "Prerequisites", that explicitly states this requirement.

**Comment by pmahnke** [comment]
@evilnick any progress updates?
