### ISSUE TITLE
Remove sudo from microk8s enable kubeflow

### ISSUE THREAD

**Issue by davecore82** [canonical-web-and-design/microk8s.io#388]
## Summary

The page https://microk8s.io/docs/addon-kubeflow gives the instructions to enable kubeflow with sudo:

`sudo microk8s enable kubeflow`

But when we run that, microk8s complains that you cannot run this command as root:

```
ubuntu@node05ob32:~$ sudo microk8s enable kubeflow --bundle lite --ignore-min-mem
This command can't be run as root.
Try `microk8s enable kubeflow` instead.
Failed to enable kubeflow
```

It works well when you don't use sudo:

```
ubuntu@node05ob32:~$ microk8s enable kubeflow --bundle lite --ignore-min-mem
Enabling dns...
Enabling storage...
Enabling ingress...
Enabling metallb:10.64.140.43-10.64.140.49...
Waiting for other addons to finish initializing...
Addon setup complete. Checking connectivity...
Bootstrapping...
Bootstrap complete.
Successfully bootstrapped, deploying...
Kubeflow deployed.
Waiting for operator pods to become ready.
Waited 0s for operator pods to come up, 31 remaining.
[...]
```

## Process

To reproduce, install MicroK8s (I'm using channel 1.19):

`sudo snap install microk8s --classic --channel=1.19`

And try to enable Kubeflow:

`sudo microk8s enable kubeflow`

## Current and expected result

The documentation should be in line with the command.

**Comment by evilnick** [comment]
hi, sorry about the delay - this was actually fixed in docs some while ago
