### ISSUE TITLE
`microk8s enable --help

### ISSUE THREAD

**Issue by baryluk** [canonical-web-and-design/microk8s.io#393]
## Summary

On the https://microk8s.io/ directly, when you expand Linux, the 3rd step says:

```

Turn on the services you want

microk8s enable dashboard dns registry istio

Try `microk8s enable --help` for a list of available services and optional features. microk8s disable <name> turns off a service.
```

The problem is, that `microk8s enable --help` doesn't list available services.

```
user@debian:~/Downloads$ sudo /snap/bin/microk8s enable --help
Usage: microk8s enable [OPTIONS] ADDONS...

  Enables a MicroK8s addon.

  For a list of available addons, run `microk8s status`.

  To see help for individual addons, run:

      microk8s enable ADDON -- --help

Options:
  --help  Show this message and exit.
```

It says to use  `microk8s status`, but that doesn't work either in many situations:

```
user@debian:~/Downloads$ sudo /snap/bin/microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
user@debian:~/Downloads$
```

**Comment by evilnick** [comment]
There are currently only two ways to see the list of available addons:
 1. Run `microk8s status` against a running version of MicroK8s
 2. Check the list [in the documentation](https://microk8s.io/docs/addons#heading--list)
 
I will fix the wrong info on the website, but it seems like that doesn't solve your issue?

**Comment by evilnick** [comment]
I am closing this in favour of filing a bug against microk8s to actually produce the expected output - https://github.com/ubuntu/microk8s/issues/2138
