### ISSUE TITLE
Pages are missing

### ISSUE THREAD

**Issue by thijsheijden** [canonical-web-and-design/microk8s.io#398]
## Summary

[Please describe the issue.]
When visiting the 'services and ports' or 'Authentication and authorization' pages of the website I get a 404.

## Process

[List the steps to replicate the issue.]
Go to https://microk8s.io/t/services-and-ports/11263#heading--auth#heading--auth#heading--auth#heading--auth

## Current and expected result

[Describe what happened and what you expected.]
What happened: I got a 404.
What I expected: A webpage explaining authentication and authorization in microk8s.

## Screenshot

[If relevant, include a screenshot.]

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]
I get a 404 in Safari, Firefox and Chrome.

**Comment by jthak002** [comment]
Yes facing the same issue. Cannot see any pages except "Getting Started"

**Comment by bttger** [comment]
Possible duplicate: https://github.com/canonical-web-and-design/microk8s.io/issues/397

**Comment by anthonydillon** [comment]
Thanks for taking the time to report this issue to us. This issue has been resolved.
