### ISSUE TITLE
Addons links is broken

### ISSUE THREAD

**Issue by kconde2** [canonical-web-and-design/microk8s.io#399]
## Summary

[Please describe the issue.]
"See the full list of addons" button is not working on this page https://microk8s.io/docs

## Process

[List the steps to replicate the issue.]

## Current and expected result

[Describe what happened and what you expected.

## Screenshot
![image](https://user-images.githubusercontent.com/43377621/113911856-c0e79800-97da-11eb-867b-e8440ca3e9b2.png)

[If relevant, include a screenshot.]

## Browser details
https://microk8s.io/t/microk8s-add-ons/11264#heading--list#heading--list
[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by kconde2** [comment]
After posting I saw it's maybe the same problem as referenced here https://github.com/canonical-web-and-design/microk8s.io/issues/398

**Comment by anthonydillon** [comment]
Thanks for taking the time to report this issue to us. This issue has been resolved.
