### ISSUE TITLE
The asciinema plugin is 1MB

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/microk8s.io#40]
Currently, all the assets that make up the asciinema video adds up to over 1MB in size. I think we should convert it into a short video showing the same thing.

**Comment by anthonydillon** [comment]
It looks like its mainly fonts. I wonder if we could stop it including so many fonts and use Ubuntu Mono.

**Comment by anasereijo** [comment]
@anthonydillon is this something you can fix?

**Comment by anthonydillon** [comment]
Only by replacing it with something else like a get started guide.
