### ISSUE TITLE
404 for microk8s.io/docs/high-availability

### ISSUE THREAD

**Issue by rbashish** [canonical-web-and-design/microk8s.io#405]
## Summary

Unable to find the reequsted page for **Microk8s Docs**

## Process

- I had been working on setting up Microk8s High availabilty using the documentation link https://microk8s.io/docs/high-availability which was working perfectly till yesterday.

## Current and expected result

But today when I tried to reach the page even from Google search result, the page is showing 404 status. Can not able to verify some setup which I had applied.

## Screenshot

![microk8s-high-availabiltiy-404](https://user-images.githubusercontent.com/6831399/116551224-55927100-a915-11eb-9fb1-f7af1ff95cc8.png)

## Browser details

I think it does not require this details

**Comment by 2er0** [comment]
In general almost all pages return a not found. :(

**Comment by anthonydillon** [comment]
Sorry about this. We have upgraded the docs module and released it. Docs should all be back online.

**Comment by rbashish** [comment]
> Sorry about this. We have upgraded the docs module and released it. Docs should all be back online.

Thanks @anthonydillon, was able to get the page the next day :+1:
