### ISSUE TITLE
Bump canonicalwebteam.discourse to 4.0.2

### ISSUE THREAD

**Issue by jpmartinspt** [canonical-web-and-design/microk8s.io#409]
## Summary
Bump discourse module to the latest version in order to fix the problem described in https://github.com/canonical-web-and-design/canonicalwebteam.discourse/issues/99 on microk8s.io/docs

## To do
@jpmartinspt  and @jkfran to work on the [new index topic](https://docs.google.com/document/d/1VCSnT6TNkqDZdYu6-80XLoyc64IKpURDi0hS0szPmcY/edit) for discourse docs v4 and to sync with evilnick to release.

**Comment by SirSamTumless** [comment]
@jpmartinspt Please point this

**Comment by jpmartinspt** [comment]
It show points for me(5)?
