### ISSUE TITLE
Offline install (1.21) fails on RHEL

### ISSUE THREAD

**Issue by just1victory** [canonical-web-and-design/microk8s.io#417]
## Summary

Relates to https://github.com/canonical-web-and-design/microk8s.io/issues/321

This an upgrade from 1.19 to 1.21

## Process

https://microk8s.io/docs/install-alternatives#heading--offline

Current results:
sudo snap ack microk8s_2210.assert

sudo install microk8s_2210.snap -classic

error: cannot perform the following tasks:
-Ensure prerequisites for "microk8s" are available (cannot install snap base "core18": Post https://api.snapcraft.io/v2/snaps/refresh: dial tcp: lookup api.snapcraft.io on xx.xx.xx.xx:53: read tcp: xx.xx.xx.xx:35831->xx.xx.xx.xx:53: i/o timeout)

So, I then downloaded the latest snap core ( https://microk8s.io/docs/install-alternatives#heading--offline ).... that retrieved core_11167.assert and core_11167.snap.   I installed them successfully I still get the same exact error (core18) described above.

Help!

## Current and expected result

[Describe what happened and what you expected.

## Screenshot

[If relevant, include a screenshot.]

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by evilnick** [comment]
Hi. Sorry to hear you had more trouble with this. I know it relates to installing MicroK8s, but seems more of an issue with the snaps not working as expected, possibly due to something in the core snap. I will have to look into that

@degville have you come across anything similar with your experience of snaps? Offline installs work fine on Ubuntu, but Fedora (and other platforms) will require the relevant core-snap. Should we be targeting a specific one?

**Comment by just1victory** [comment]
I eventually got 1.21 to work by installing **both** snap core & snap core18.  Now we are stuck with this 
 ( https://github.com/ubuntu/microk8s/issues/2361 ) issue and cannot get any traction on it (fix is included in the writeup).   Trying not to be sarcastic, but "MicroK8s is the simplest production-grade upstream K8s" doesn't ring true anymore.   FIPS is more common everyday and free to install/test against.  Please help if you can by raising awareness of FIPS compatibility with your product owners.

**Comment by pmahnke** [comment]
clossing this as it is being looked at on the above issue.
