### ISSUE TITLE
storageclass.storage.k8s.io "openebs-jiva-default" not found

### ISSUE THREAD

**Issue by alphabet5** [canonical-web-and-design/microk8s.io#503]
## Summary

Documentation [here](https://microk8s.io/docs/addon-openebs) states to use `openebs-jiva-default` as the storage class for multi-node clusters. This storage class doesn't exist.

## Process

- install microk8s
- enable openebs
- kubectl get storageclasses

## Current and expected result

I would expect the documentation to show usage for `openebs-jiva-csi-default` or `openebs-jiva-default` to exist as a storage class.

## Screenshot

```bash
% kubectl get storageclasses
NAME                          PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
microk8s-hostpath (default)   microk8s.io/hostpath   Delete          Immediate              false                  53d
openebs-hostpath              openebs.io/local       Delete          WaitForFirstConsumer   false                  53d
openebs-jiva-csi-default      jiva.csi.openebs.io    Delete          Immediate              true                   53d
openebs-device                openebs.io/local       Delete          WaitForFirstConsumer   false                  53d
```

**Comment by sowasred2012** [comment]
@evilnick could you help us with this one please?

**Comment by evilnick** [comment]
It seems the add-on created a class with a different name when using prior versions of Kubernetes. Thanks for mentioning this @alphabet5, as well as adding a note I have added some examples and improved that page.

**Comment by alphabet5** [comment]
Some additional information in case someone visits this page in the future. It looks like it was depreciated here in favor of the csi driver. 

```
Deprecation Notice: Jiva and cStor out-of-tree external provisioners will be deprecated by Dec 2021 in favor of the corresponding CSI Drivers. The out of tree provisioners for Jiva and cStor will stop working from Kubernetes 1.22 and forward as the version of the custom resources used by those provisioners will be deprecated. We strongly recommend you plan for migrating your volumes to [cStor CSI](https://github.com/openebs/upgrade/blob/master/docs/migration.md) or [Jiva CSI](https://github.com/openebs/upgrade/blob/master/docs/migration.md#migrating-jiva-external-provisioned-volumes-to-jiva-csi-volumes-experimental) as early as possible.
```

https://github.com/openebs/openebs/discussions/3446
