### ISSUE TITLE
Malformed table in narrow widths

### ISSUE THREAD

**Issue by sed-i** [canonical-web-and-design/microk8s.io#506]
## Summary
The table in `https://microk8s.io/compare` gets malformed when browser window is narrow, or on mobile (even in landscape mode).

## Process
Go to https://microk8s.io/compare and reduce width, or open https://microk8s.io/compare on a mobile device.

## Current and expected result
Table is entirely restructured and headers are dropped - can't tell which is which.

## Screenshot
Wide enough:
![ok](https://user-images.githubusercontent.com/82407168/155233442-f85e229b-d1c4-4417-b66d-5c331a685af5.png)

Slightly too narrow:
![malformed](https://user-images.githubusercontent.com/82407168/155233493-b0c0590c-e1cc-4f34-936e-7501ef24ba19.png)

## Browser details
Including but not limited to:
- Firefox 97.0.1 (64-bit) - Snap for Ubuntu

**Comment by petesfrench** [comment]
@davegoddard42 I have removed the `mobile-card` class from the table so it retains the same style and I think it is still very readable. Is this what you had in mind? you can see it here: https://microk8s-io-509.demos.haus/compare

**Comment by davegoddard42** [comment]
@petesfrench - there's some cut off on mobile resolutions of longer words - the elipsis (...) is used which isn't great.

<img width="483" alt="image" src="https://user-images.githubusercontent.com/25453620/157028886-5967e784-c641-4e91-915f-85b0e17d5e44.png">

Is there a simple way to tackle that? Or do I need to look into some solutions?

The mobile-card class has other issues too - it removes the column titles, so a user wouldn't know which row aligns with which product. So we definitely shouldn't be using that either, in this instance. 

<img width="376" alt="image" src="https://user-images.githubusercontent.com/25453620/157029102-826610ae-0770-4ea6-a6b8-820cbd1ae42e.png">

My current thinking is that we make use of the mobile-card class, but only for very small screens (mobile devices) and we somehow include the column header in the card.

**Comment by petesfrench** [comment]
@davegoddard42 so I updated the pattern to vanilla-3.0 and that has changed it to look like this: 
![image](https://user-images.githubusercontent.com/58276363/157043431-1295dab0-70ac-47c4-9d5d-dd533859d6dd.png)
Is that any better or still not quite right?

**Comment by davegoddard42** [comment]
@petesfrench yes - that's much better. But I think the breakpoint where it switches to card mode isn't right. It looks fine as a table until the words start using ellipsis (about 485px width I think?). Is the breakpoint set in the class?

**Comment by petesfrench** [comment]
@davegoddard42 it is set in the class, but you are right that is too big for mobile. I will raise it as an issue on vanilla, as that should probably be changed to 485px. Should we merge this how it is and when vanilla is updated the table should be to? Or do you think this needs a fix now?

**Comment by davegoddard42** [comment]
Apologies @petesfrench for the late reply. I think we should merge it as it is now, as it does solve the issue in question. We can revisit once vanilla is updated.
