### ISSUE TITLE
How to upgrade kubernetes version under Windows? 

### ISSUE THREAD

**Issue by BaerSy** [canonical-web-and-design/microk8s.io#508]
## Summary

I installed Microk8s for Windows. When I tried to deploy application with helm3 , I found error with k8s version not compatible. How can I upgrade k8s within microk8s under windows. I can't find snap refresh in microk8s for windows.  

Thanks

**Comment by cristinadresch** [comment]
Could you please add this issue here instead? https://github.com/canonical/microk8s This repo here is only for the website.
