### ISSUE TITLE
404 error, bad link on on /docs

### ISSUE THREAD

**Issue by AlexanderNorris** [canonical-web-and-design/microk8s.io#512]
## Summary

The https://microk8s.io/docs page has a bad link under "In this documentation" when selecting "Tutorials" which results in a 404.

## Process

1) Browse to https://microk8s.io/docs
2) Click the Tutorials link on the page under "In this documentation"

## Current and expected result

404 error, should link somewhere else.

## Screenshot

![image](https://user-images.githubusercontent.com/47463538/159155797-01628b29-b2e9-4a82-a51b-f7eb3a87181e.png)

## Browser details

N/A

**Comment by anthonydillon** [comment]
@evilnick could you update the links to make them all work across discourse and the rendered docs?

**Comment by evilnick** [comment]
This was already fixed
