### ISSUE TITLE
Update table on microk8s.io/compare

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/microk8s.io#534]
## Summary

Please update /compare page as per  revised copydoc: https://docs.google.com/document/d/1wWos3iWMTCqDbxZBDuSVqvY6ZwYux-goCrX0L0E5Weo

**Comment by petesfrench** [comment]
@evilnick Is this for you?

**Comment by evilnick** [comment]
I didn't change the copydoc, no

**Comment by evilnick** [comment]
Oh, I see. Do you mean am I doing it?  No

**Comment by petesfrench** [comment]
Ok, could you link the copydoc in the issue please and I will add it to next iteration

**Comment by evilnick** [comment]
here you go https://docs.google.com/document/d/1wWos3iWMTCqDbxZBDuSVqvY6ZwYux-goCrX0L0E5Weo
