### ISSUE TITLE
Add expandable navigation

### ISSUE THREAD

**Issue by evilnick** [canonical-web-and-design/microk8s.io#538]
## Summary

Please add expandable navigation to the docs

**Comment by mtruj013** [comment]
Blocked pending the next Vanilla release

**Comment by evilnick** [comment]
@mtruj013 is there any sense of when this may be possible? There are important changes to docs we have been holding off because this was "nearly ready"

**Comment by carkod** [comment]
https://github.com/canonical-web-and-design/anbox-cloud.io has it, we probably just need to update CSS classes
