### ISSUE TITLE
Kubernetes image is not retina / high def

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/microk8s.io#66]
The Kubernetes image in the hero area is not high definition for retina screens.
<img width="1022" alt="screenshot 2019-02-20 at 12 16 10" src="https://user-images.githubusercontent.com/1953388/53088212-63643480-3509-11e9-89b5-b1e7d553f84a.png">

**Comment by anasereijo** [comment]
Thanks, @clagom for filling this issue

the image should be replaced with the[ SVG version](https://assets.ubuntu.com/v1/96d35aa4-certified-kubernetes-logo.svg)
