### ISSUE TITLE
args folder is missing

### ISSUE THREAD

**Issue by Zikoel** [canonical-web-and-design/microk8s.io#73]
In the index.md there is a mention about `${SNAP_DATA}/args/kube-apiserver` configuration but in the actual microk8s release `1.14.1 rev 522` the folder `args` doesn't exist. Moreover there are two places where the same configurations are present:

* `/snap/microk8s/current/default-args`
* `/snap/microk8s/current/microk8s-resources/default-args`

What is the effective args folder ?

**Comment by ktsakalozos** [comment]
Hi @Zikoel,

Normally, `${SNAP_DATA}` points to `/var/snap/microk8s/current` so you should find `kube-apiserver` under `/var/snap/microk8s/current/args/kube-apiserver`.

The folders `/snap/microk8s/current/default-args` and `/snap/microk8s/current/microk8s-resources/default-args` are in a read-only directory and serve as a safe-copy with which we initialize the arguments under `${SNAP_DATA}/args/`.

**Comment by Zikoel** [comment]
Yes you are right my problem is that I can't find `${SNAP_DATA}` in my envs! This issue can be close for me!

**Comment by ktsakalozos** [comment]
`${SNAP_DATA}` is available to the snap at runtime. See https://docs.snapcraft.io/environment-variables/7983 for the full list of such variables.
