### ISSUE TITLE
Certified logo is broken

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-web-and-design/microk8s.io#78]
https://microk8s.io/docs/

links to https://raw.githubusercontent.com/cncf/artwork/master/kubernetes/certified-kubernetes/versionless/color/certified-kubernetes-color.png which is broken.

![image](https://user-images.githubusercontent.com/246192/57681565-3c149380-7630-11e9-9bcc-159a89acb03d.png)

Firefox 66.0.3, on Ubuntu 18.10 Cosmic Cuttlefish

**Comment by ktsakalozos** [comment]
Thank you for reporting this @sparkiegeek . This is fixed in https://github.com/canonical-web-and-design/microk8s.io/pull/75 . Can we have a deployment of the site?

**Comment by anthonydillon** [comment]
This is now live
