### ISSUE TITLE
Should we redirect from microk8s.com

### ISSUE THREAD

**Issue by ktsakalozos** [canonical-web-and-design/microk8s.io#84]
Should we redirect traffic going to microk8s.com to microk8s.io? Is this something we do or we just say ".io is the only right location"?

**Comment by anthonydillon** [comment]
Good idea, I have raised an RT to have the redirect put in place.

**Comment by anthonydillon** [comment]
Waiting on an RT to complete

**Comment by cristinadresch** [comment]
This has been complete
